"""autogenerated by genpy from phidgets/pidRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pidRequest(genpy.Message):
  _md5sum = "f158fdeeb607b097858cf374d60a5921"
  _type = "phidgets/pidRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 index
int32 mode
int32 direction
int32 target_position
float32 target_velocity
float32 p_gain
float32 i_gain
float32 d_gain
float32 acc_ff
float32 fri_ff
float32 vel_ff
float32 hold
float32 bias
float32 accel
float32 trans
float32 lag
float32 min
float32 max
float32 slew

"""
  __slots__ = ['index','mode','direction','target_position','target_velocity','p_gain','i_gain','d_gain','acc_ff','fri_ff','vel_ff','hold','bias','accel','trans','lag','min','max','slew']
  _slot_types = ['int32','int32','int32','int32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       index,mode,direction,target_position,target_velocity,p_gain,i_gain,d_gain,acc_ff,fri_ff,vel_ff,hold,bias,accel,trans,lag,min,max,slew

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pidRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.index is None:
        self.index = 0
      if self.mode is None:
        self.mode = 0
      if self.direction is None:
        self.direction = 0
      if self.target_position is None:
        self.target_position = 0
      if self.target_velocity is None:
        self.target_velocity = 0.
      if self.p_gain is None:
        self.p_gain = 0.
      if self.i_gain is None:
        self.i_gain = 0.
      if self.d_gain is None:
        self.d_gain = 0.
      if self.acc_ff is None:
        self.acc_ff = 0.
      if self.fri_ff is None:
        self.fri_ff = 0.
      if self.vel_ff is None:
        self.vel_ff = 0.
      if self.hold is None:
        self.hold = 0.
      if self.bias is None:
        self.bias = 0.
      if self.accel is None:
        self.accel = 0.
      if self.trans is None:
        self.trans = 0.
      if self.lag is None:
        self.lag = 0.
      if self.min is None:
        self.min = 0.
      if self.max is None:
        self.max = 0.
      if self.slew is None:
        self.slew = 0.
    else:
      self.index = 0
      self.mode = 0
      self.direction = 0
      self.target_position = 0
      self.target_velocity = 0.
      self.p_gain = 0.
      self.i_gain = 0.
      self.d_gain = 0.
      self.acc_ff = 0.
      self.fri_ff = 0.
      self.vel_ff = 0.
      self.hold = 0.
      self.bias = 0.
      self.accel = 0.
      self.trans = 0.
      self.lag = 0.
      self.min = 0.
      self.max = 0.
      self.slew = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_4i15f.pack(_x.index, _x.mode, _x.direction, _x.target_position, _x.target_velocity, _x.p_gain, _x.i_gain, _x.d_gain, _x.acc_ff, _x.fri_ff, _x.vel_ff, _x.hold, _x.bias, _x.accel, _x.trans, _x.lag, _x.min, _x.max, _x.slew))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 76
      (_x.index, _x.mode, _x.direction, _x.target_position, _x.target_velocity, _x.p_gain, _x.i_gain, _x.d_gain, _x.acc_ff, _x.fri_ff, _x.vel_ff, _x.hold, _x.bias, _x.accel, _x.trans, _x.lag, _x.min, _x.max, _x.slew,) = _struct_4i15f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_4i15f.pack(_x.index, _x.mode, _x.direction, _x.target_position, _x.target_velocity, _x.p_gain, _x.i_gain, _x.d_gain, _x.acc_ff, _x.fri_ff, _x.vel_ff, _x.hold, _x.bias, _x.accel, _x.trans, _x.lag, _x.min, _x.max, _x.slew))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 76
      (_x.index, _x.mode, _x.direction, _x.target_position, _x.target_velocity, _x.p_gain, _x.i_gain, _x.d_gain, _x.acc_ff, _x.fri_ff, _x.vel_ff, _x.hold, _x.bias, _x.accel, _x.trans, _x.lag, _x.min, _x.max, _x.slew,) = _struct_4i15f.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_4i15f = struct.Struct("<4i15f")
"""autogenerated by genpy from phidgets/pidResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class pidResponse(genpy.Message):
  _md5sum = "35e806e08fe8e25fde5b4c88fa52f05b"
  _type = "phidgets/pidResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 ack


"""
  __slots__ = ['ack']
  _slot_types = ['int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       ack

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(pidResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.ack is None:
        self.ack = 0
    else:
      self.ack = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_struct_i.pack(self.ack))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 4
      (self.ack,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_struct_i.pack(self.ack))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 4
      (self.ack,) = _struct_i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_i = struct.Struct("<i")
class pid(object):
  _type          = 'phidgets/pid'
  _md5sum = '095b14b7e37aa3b1f86557d3dcc10fde'
  _request_class  = pidRequest
  _response_class = pidResponse
